### ISSUE TITLE
開發計劃

### ISSUE THREAD

**Issue by imlinhanchao** [imlinhanchao/pwl-chat#3]

**Comment by imlinhanchao** [comment]
### feature
- #2 
- ~同步摸魚派表情包~
- 設置界面
- 指定信息屏蔽
- 消息提醒設置
- ~紅包 0 溢提示~
- ~紅包連發~
- 紅包跟隨
- ~点歌网易云~
- 主题设置自定义
- 弹幕模式
- 自動更新機制
- #4 
- 識別摸魚派圖片鏈接，客戶端打開大圖
- #5

**Comment by imlinhanchao** [comment]
### bug
- ~粘貼出現 undefined~
- ~紅包出現復讀按鈕~
- ~無法粘貼QQ複製圖片~
- ~多个最佳红包~
- ~未抢完出现最佳红包~
- ~紅包消息會打斷復讀~
- ~較寬而扁的圖點開大圖看不到~
- ~消息内容比較多時，+1按鈕會被擠壓~

**Comment by Lemon-cxh** [comment]
启用置顶，重启后置顶失效，需要关闭再启用

**Comment by imlinhanchao** [comment]
> 启用置顶，重启后置顶失效，需要关闭再启用

@Lemon-cxh 重啓是指電腦重啓嗎？

**Comment by Lemon-cxh** [comment]
> 
应用重启

**Comment by imlinhanchao** [comment]
> > 
> 
> 应用重启

Win10 沒有復現，難道是Win11才會 🤨

**Comment by csfwff** [comment]
再增加个清屏，清空历史消息

**Comment by imlinhanchao** [comment]
Move to [Project](https://github.com/imlinhanchao/pwl-chat/projects/1)
